language:
   - java
after_sucess:
- sudo apt update -y 
- sudo apt install sshpass -y  
- sshpass -p ${Password} ssh -o stricthostkeychecking=no travis@${IPADDR} "cd /home/travis && sudo sh deploy.sh"
